### ISSUE TITLE
Removing let from a local variable causes name error

### ISSUE THREAD

**Issue by philipdexter** [scizzorz/rain#16]
```
main = func()
  a = 1
  print a
```

```Exception: Undeclared <name_node('a')>```

**Comment by scizzorz** [comment]
An artifact of the original purpose of `let` - to force shadowing.

It still may be useful to prevent some typos, ie:

```
main = func()
  let initializer = 3
  ...
  initalizer = 4 # spelled wrong
```

**Comment by philipdexter** [comment]
Sounds like a feature
